### ISSUE TITLE
Crash on android 6

### ISSUE THREAD

**Issue by hoangtuancntt** [java-diff-utils/java-diff-utils#167]
I got a error when run app on android 6 in detail below
Fatal Exception: java.lang.NoClassDefFoundError: com.github.difflib.algorithm.myers.MeyersDiff$$ExternalSyntheticLambda0
       at com.github.difflib.algorithm.myers.MeyersDiff.<init>(MeyersDiff.java:37)
       at com.github.difflib.algorithm.myers.MeyersDiff$1.create(MeyersDiff.java:190)
       at com.github.difflib.DiffUtils.diff(DiffUtils.java:62)

**Comment by wumpz** [comment]
Since Android 6 uses  Java 7 this version of java-diff-utils could not be used since it is build with JDK 8 and uses JDK 8 API as well.
