### ISSUE TITLE
Crash below Android 7

### ISSUE THREAD

**Issue by Micoder-dev** [java-diff-utils/java-diff-utils#192]
java.lang.NoClassDefFoundError: com.github.difflib.algorithm.myers.MeyersDiff$$ExternalSyntheticLambda0
	at com.github.difflib.algorithm.myers.MeyersDiff.<init>(MeyersDiff.java:37)
	at com.github.difflib.algorithm.myers.MeyersDiff$1.create(MeyersDiff.java:190)
	at com.github.difflib.DiffUtils.diff(DiffUtils.java:62)
	at com.vexora.compareme.main.screens.CompareScreenKt.FileComparisonDetailView(CompareScreen.kt:743)
	at com.vexora.compareme.main.screens.CompareScreenKt.FileDetailView(CompareScreen.kt:668)
	at com.vexora.compareme.main.screens.CompareScreenKt$CompareScreen$6.invoke(CompareScreen.kt:329)
	at com.vexora.compareme.main.screens.CompareScreenKt$CompareScreen$6.invoke(CompareScreen.kt:294)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.material3.NavigationDrawerKt.ModalNavigationDrawer-FHprtrg(NavigationDrawer.kt:343)
	at androidx.compose.material3.NavigationDrawerKt$ModalNavigationDrawer$3.invoke(NavigationDrawer.kt)
	at androidx.compose.material3.NavigationDrawerKt$ModalNavigationDrawer$3.invoke(NavigationDrawer.kt)
	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:192)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2823)
	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:3114)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3605)
	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3550)
	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:948)
	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1206)
	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:132)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:616)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:585)
	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:765)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:549)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@2aec11ef, androidx.compose.ui.platform.MotionDurationScaleImpl@1d4a4fc, StandaloneCoroutine{Cancelling}@28b73785, AndroidUiDispatcher@1ecb59da]

**Comment by wumpz** [comment]
This exception happens if there are not all Java 8 possibilities available. So which version does Android <7 support.
